### ISSUE TITLE
Should specification include a "metadata" field

### ISSUE THREAD

**Issue by matthewhudson** [microservices/openmicroservices.org#166]
> **TLDR;** I propose adding a free-form, top-level `meta` field to the specification.

In a world w/ more than one hub, each hub may have unique requirements for submitting microservices.
For example, the Storyscript Hub may one day allow developers to [submit custom images](https://github.com/storyscript/hub/issues/18) to represent their service.

Presently, the Storyscript Hub allows developers to submit services with special "meta" data such as; tags, category (w/ our own custom taxonomy), docker tag, service name, and description. Other hubs may want to be able to reuse these fields, and/or have additional fields as well. 

Or maybe instead of re-using these fields, some of these hypothetical hubs may have unique requirements for categories (their own taxonomy), or maybe prefer  an image with different dimensions, aspect ratio, file format, byte size limit, etc.

This proposed `meta` field could have all kinds of use-cases, far beyond just "other hubs". I doubt we're even capable of thinking of all the possible permutations people will come up with. 

```yaml
meta:
  storyscript:
     hub_image_url: https://domain.tld/200x200.png
     hub_cover_image_url: https://domain.tld/400x1000.png
     category: Text Processing
  some_other_hub:
     image_url: https://domain.tld/600x600.jpg 
     other_image_url: https://domain.tld/50x50.jpg
     source_code: https://github.com/user/repo
     support_email: support@domain.tld
  yet_another_hub:
     background_color: #453223
     emoji: &#x231B;
     verb: capture
     noun: webpage
     object: screenshot
```

More TKTKTK, just wanted to share some initial thoughts.
