### ISSUE TITLE
Add "deprecated" boolean to action, argument and output

### ISSUE THREAD

**Issue by stevepeak** [microservices/openmicroservices.org#57]
Adding deprecated can help transition users to other actions/args/outs.

```yml
actions:
  foobar:
    deprecated: true
    help: Please use this other command.
```
